/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEmployerRouteImport } from './routes/_authenticated/employer'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as AuthenticatedApplyJobIdRouteImport } from './routes/_authenticated/apply.$jobId'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardApplicationsRouteImport } from './routes/_authenticated/dashboard.applications'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardResumeRouteImport } from './routes/_authenticated/dashboard.resume'
import { Route as AuthenticatedDashboardSavedRouteImport } from './routes/_authenticated/dashboard.saved'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedEmployerIndexRouteImport } from './routes/_authenticated/employer.index'
import { Route as AuthenticatedEmployerApplicationsRouteImport } from './routes/_authenticated/employer.applications'
import { Route as AuthenticatedEmployerCompanyRouteImport } from './routes/_authenticated/employer.company'
import { Route as AuthenticatedEmployerPostRouteImport } from './routes/_authenticated/employer.post'
import { Route as AuthenticatedEmployerSettingsRouteImport } from './routes/_authenticated/employer.settings'
import { Route as AuthenticatedEmployerJobsIndexRouteImport } from './routes/_authenticated/employer.jobs.index'
import { Route as AuthenticatedEmployerJobsJobIdEditRouteImport } from './routes/_authenticated/employer.jobs.$jobId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployerRoute = AuthenticatedEmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApplyJobIdRoute = AuthenticatedApplyJobIdRouteImport.update({
  id: '/apply/$jobId',
  path: '/apply/$jobId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardApplicationsRoute =
  AuthenticatedDashboardApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardResumeRoute =
  AuthenticatedDashboardResumeRouteImport.update({
    id: '/resume',
    path: '/resume',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSavedRoute =
  AuthenticatedDashboardSavedRouteImport.update({
    id: '/saved',
    path: '/saved',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedEmployerIndexRoute =
  AuthenticatedEmployerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerApplicationsRoute =
  AuthenticatedEmployerApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerCompanyRoute =
  AuthenticatedEmployerCompanyRouteImport.update({
    id: '/company',
    path: '/company',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerPostRoute =
  AuthenticatedEmployerPostRouteImport.update({
    id: '/post',
    path: '/post',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerSettingsRoute =
  AuthenticatedEmployerSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerJobsIndexRoute =
  AuthenticatedEmployerJobsIndexRouteImport.update({
    id: '/jobs/',
    path: '/jobs/',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerJobsJobIdEditRoute =
  AuthenticatedEmployerJobsJobIdEditRouteImport.update({
    id: '/jobs/$jobId/edit',
    path: '/jobs/$jobId/edit',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/companies': typeof CompaniesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/employer': typeof AuthenticatedEmployerRouteWithChildren
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/apply/$jobId': typeof AuthenticatedApplyJobIdRoute
  '/dashboard/applications': typeof AuthenticatedDashboardApplicationsRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/resume': typeof AuthenticatedDashboardResumeRoute
  '/dashboard/saved': typeof AuthenticatedDashboardSavedRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/employer/applications': typeof AuthenticatedEmployerApplicationsRoute
  '/employer/company': typeof AuthenticatedEmployerCompanyRoute
  '/employer/post': typeof AuthenticatedEmployerPostRoute
  '/employer/settings': typeof AuthenticatedEmployerSettingsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/employer/': typeof AuthenticatedEmployerIndexRoute
  '/employer/jobs/': typeof AuthenticatedEmployerJobsIndexRoute
  '/employer/jobs/$jobId/edit': typeof AuthenticatedEmployerJobsJobIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/companies': typeof CompaniesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs': typeof JobsIndexRoute
  '/apply/$jobId': typeof AuthenticatedApplyJobIdRoute
  '/dashboard/applications': typeof AuthenticatedDashboardApplicationsRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/resume': typeof AuthenticatedDashboardResumeRoute
  '/dashboard/saved': typeof AuthenticatedDashboardSavedRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/employer/applications': typeof AuthenticatedEmployerApplicationsRoute
  '/employer/company': typeof AuthenticatedEmployerCompanyRoute
  '/employer/post': typeof AuthenticatedEmployerPostRoute
  '/employer/settings': typeof AuthenticatedEmployerSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/employer': typeof AuthenticatedEmployerIndexRoute
  '/employer/jobs': typeof AuthenticatedEmployerJobsIndexRoute
  '/employer/jobs/$jobId/edit': typeof AuthenticatedEmployerJobsJobIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/companies': typeof CompaniesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/employer': typeof AuthenticatedEmployerRouteWithChildren
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/_authenticated/apply/$jobId': typeof AuthenticatedApplyJobIdRoute
  '/_authenticated/dashboard/applications': typeof AuthenticatedDashboardApplicationsRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/resume': typeof AuthenticatedDashboardResumeRoute
  '/_authenticated/dashboard/saved': typeof AuthenticatedDashboardSavedRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/employer/applications': typeof AuthenticatedEmployerApplicationsRoute
  '/_authenticated/employer/company': typeof AuthenticatedEmployerCompanyRoute
  '/_authenticated/employer/post': typeof AuthenticatedEmployerPostRoute
  '/_authenticated/employer/settings': typeof AuthenticatedEmployerSettingsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/employer/': typeof AuthenticatedEmployerIndexRoute
  '/_authenticated/employer/jobs/': typeof AuthenticatedEmployerJobsIndexRoute
  '/_authenticated/employer/jobs/$jobId/edit': typeof AuthenticatedEmployerJobsJobIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/companies'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/employer'
    | '/jobs/$jobId'
    | '/jobs/'
    | '/apply/$jobId'
    | '/dashboard/applications'
    | '/dashboard/profile'
    | '/dashboard/resume'
    | '/dashboard/saved'
    | '/dashboard/settings'
    | '/employer/applications'
    | '/employer/company'
    | '/employer/post'
    | '/employer/settings'
    | '/dashboard/'
    | '/employer/'
    | '/employer/jobs/'
    | '/employer/jobs/$jobId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/companies'
    | '/reset-password'
    | '/admin'
    | '/jobs/$jobId'
    | '/jobs'
    | '/apply/$jobId'
    | '/dashboard/applications'
    | '/dashboard/profile'
    | '/dashboard/resume'
    | '/dashboard/saved'
    | '/dashboard/settings'
    | '/employer/applications'
    | '/employer/company'
    | '/employer/post'
    | '/employer/settings'
    | '/dashboard'
    | '/employer'
    | '/employer/jobs'
    | '/employer/jobs/$jobId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/companies'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/employer'
    | '/jobs/$jobId'
    | '/jobs/'
    | '/_authenticated/apply/$jobId'
    | '/_authenticated/dashboard/applications'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/resume'
    | '/_authenticated/dashboard/saved'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/employer/applications'
    | '/_authenticated/employer/company'
    | '/_authenticated/employer/post'
    | '/_authenticated/employer/settings'
    | '/_authenticated/dashboard/'
    | '/_authenticated/employer/'
    | '/_authenticated/employer/jobs/'
    | '/_authenticated/employer/jobs/$jobId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CompaniesRoute: typeof CompaniesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer': {
      id: '/_authenticated/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof AuthenticatedEmployerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/apply/$jobId': {
      id: '/_authenticated/apply/$jobId'
      path: '/apply/$jobId'
      fullPath: '/apply/$jobId'
      preLoaderRoute: typeof AuthenticatedApplyJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/applications': {
      id: '/_authenticated/dashboard/applications'
      path: '/applications'
      fullPath: '/dashboard/applications'
      preLoaderRoute: typeof AuthenticatedDashboardApplicationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/resume': {
      id: '/_authenticated/dashboard/resume'
      path: '/resume'
      fullPath: '/dashboard/resume'
      preLoaderRoute: typeof AuthenticatedDashboardResumeRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/saved': {
      id: '/_authenticated/dashboard/saved'
      path: '/saved'
      fullPath: '/dashboard/saved'
      preLoaderRoute: typeof AuthenticatedDashboardSavedRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/employer/': {
      id: '/_authenticated/employer/'
      path: '/'
      fullPath: '/employer/'
      preLoaderRoute: typeof AuthenticatedEmployerIndexRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/applications': {
      id: '/_authenticated/employer/applications'
      path: '/applications'
      fullPath: '/employer/applications'
      preLoaderRoute: typeof AuthenticatedEmployerApplicationsRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/company': {
      id: '/_authenticated/employer/company'
      path: '/company'
      fullPath: '/employer/company'
      preLoaderRoute: typeof AuthenticatedEmployerCompanyRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/post': {
      id: '/_authenticated/employer/post'
      path: '/post'
      fullPath: '/employer/post'
      preLoaderRoute: typeof AuthenticatedEmployerPostRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/settings': {
      id: '/_authenticated/employer/settings'
      path: '/settings'
      fullPath: '/employer/settings'
      preLoaderRoute: typeof AuthenticatedEmployerSettingsRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/jobs/': {
      id: '/_authenticated/employer/jobs/'
      path: '/jobs'
      fullPath: '/employer/jobs/'
      preLoaderRoute: typeof AuthenticatedEmployerJobsIndexRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/jobs/$jobId/edit': {
      id: '/_authenticated/employer/jobs/$jobId/edit'
      path: '/jobs/$jobId/edit'
      fullPath: '/employer/jobs/$jobId/edit'
      preLoaderRoute: typeof AuthenticatedEmployerJobsJobIdEditRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardApplicationsRoute: typeof AuthenticatedDashboardApplicationsRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardResumeRoute: typeof AuthenticatedDashboardResumeRoute
  AuthenticatedDashboardSavedRoute: typeof AuthenticatedDashboardSavedRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardApplicationsRoute:
      AuthenticatedDashboardApplicationsRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardResumeRoute: AuthenticatedDashboardResumeRoute,
    AuthenticatedDashboardSavedRoute: AuthenticatedDashboardSavedRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedEmployerRouteChildren {
  AuthenticatedEmployerApplicationsRoute: typeof AuthenticatedEmployerApplicationsRoute
  AuthenticatedEmployerCompanyRoute: typeof AuthenticatedEmployerCompanyRoute
  AuthenticatedEmployerPostRoute: typeof AuthenticatedEmployerPostRoute
  AuthenticatedEmployerSettingsRoute: typeof AuthenticatedEmployerSettingsRoute
  AuthenticatedEmployerIndexRoute: typeof AuthenticatedEmployerIndexRoute
  AuthenticatedEmployerJobsIndexRoute: typeof AuthenticatedEmployerJobsIndexRoute
  AuthenticatedEmployerJobsJobIdEditRoute: typeof AuthenticatedEmployerJobsJobIdEditRoute
}

const AuthenticatedEmployerRouteChildren: AuthenticatedEmployerRouteChildren = {
  AuthenticatedEmployerApplicationsRoute:
    AuthenticatedEmployerApplicationsRoute,
  AuthenticatedEmployerCompanyRoute: AuthenticatedEmployerCompanyRoute,
  AuthenticatedEmployerPostRoute: AuthenticatedEmployerPostRoute,
  AuthenticatedEmployerSettingsRoute: AuthenticatedEmployerSettingsRoute,
  AuthenticatedEmployerIndexRoute: AuthenticatedEmployerIndexRoute,
  AuthenticatedEmployerJobsIndexRoute: AuthenticatedEmployerJobsIndexRoute,
  AuthenticatedEmployerJobsJobIdEditRoute:
    AuthenticatedEmployerJobsJobIdEditRoute,
}

const AuthenticatedEmployerRouteWithChildren =
  AuthenticatedEmployerRoute._addFileChildren(
    AuthenticatedEmployerRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedEmployerRoute: typeof AuthenticatedEmployerRouteWithChildren
  AuthenticatedApplyJobIdRoute: typeof AuthenticatedApplyJobIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedEmployerRoute: AuthenticatedEmployerRouteWithChildren,
  AuthenticatedApplyJobIdRoute: AuthenticatedApplyJobIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CompaniesRoute: CompaniesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  JobsIndexRoute: JobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
